BE_converter/urls.py
from django.urls import path
from . import views

app_name = 'BE_converter'

urlpatterns = [

   path('ex/', views.equation_main, name='expression-main-view'),
   path('tb/', views.index, name='main-view'),
   path('lc/', views.logic_circuit, name='circuit-main-view'),
   path('convert/', views.convert_truth_table, name='convert-view'),
   path('equation_operation/', views.convert_expression, name='expression-view'),
   path('ciruit_operation/', views.convert_circuit, name='circuit-view'),

]

Home/urls.py
from django.urls import path
from . import views

app_name = 'Home'

urlpatterns = [
    
    path('register/', views.register, name="register"),
	path('login/', views.loginpage, name="login"),  
    path('logout/', views.logoutuser, name="logout"),
   path('', views.index, name='main-view'),
   path('home/', views.home1, name='home1-view'),
   path('about/', views.about, name='about-view'),
   path('help/', views.help, name='help-view'),
  

]

converter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls', namespace='Home')),
    path('BE_converter/', include('BE_converter.urls', namespace='BE_converter')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

BE_converter/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Boolean_Expression(models.Model):
    expression = models.CharField(max_length=1000)
    image = models.ImageField(upload_to='', null=True)
    created_date_time = models.DateTimeField(auto_now=False, auto_now_add=False, default=timezone.now)

Home/models.py
from django.db import models

# Create your models here.

Home/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms



class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

BE_converter/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .convert import min_terms # to calculate minimized expr from truth table, used in convert_truthtbale view
from .diagram import draw #used in convert_truthtable view for drawing circuit diagram from table
from .exp_to_circuit import easy_draw #for drawing circuit from expression, in convert expression view (similar to .diagram)
from .generate_table_array import Truthtable #to create truth table from expression in convert_circuit and convert_expression views
from .models import Boolean_Expression
from .circuit_to_exp import create_expr # to form expression from circuit,in last view of convert_circuit
# Create your views here.

def index(request):
    return render(request, 'BE_converter/main.html')

def convert_truth_table(request):
    if request.is_ajax():
        minterms = []
        data = request.POST
        data_ = dict(data.lists()) #convert querydictionary into ordinary dictionary
        data_.pop('csrfmiddlewaretoken')
        for name,value in data_.items():
            if value[0] == '1':
                minterms.append(int(name)) #extracting minterms
        total_inputs=(len(data_)/2)
        boolean_expression = min_terms(minterms,total_inputs)
       # boolean_expression = min_terms(minterms)
        result = ' + '.join(''.join(i) for i in boolean_expression)
        Boolean_Expression.objects.create(expression=result) #creating expression
        expression_pk = Boolean_Expression.objects.latest('pk') #primary key of expression just created
        circuit_image_path = draw(boolean_expression, expression_pk) #creating circuit diagram
        print(circuit_image_path)
        return JsonResponse({ 'results': result,
                                'expression': boolean_expression,
                                'image': circuit_image_path})

def equation_main(request):
    return render(request, 'BE_converter/user_equation.html')

def convert_expression(request):
    if request.is_ajax():
        data = request.POST
        result = dict(data) #convert querydictionary into ordinary dictionary
        result.pop('csrfmiddlewaretoken')
        result2=str(result)
        result2=result2.replace("[","")
        result2=result2.replace("]","")
        Boolean_Expression.objects.create(expression=str(result2))
        expression_pk = Boolean_Expression.objects.latest('pk') #primary key of expression just created
        circuit_image_path = easy_draw(result, expression_pk) #creating circuit diagram and fetch its key
        table_array,variables= Truthtable (result) #creating output truth table array  and the variables array
        return JsonResponse({ 'results': table_array,
                                'variables':variables,
                                'image': circuit_image_path})

def logic_circuit(request):
    return render(request, 'BE_converter/logic_circuit.html')

def convert_circuit(request):
    if request.is_ajax():
        data = request.POST
        input = dict(data) #convert querydictionary into ordinary dictionary
        input.pop('csrfmiddlewaretoken')
        express=create_expr(input)
        print("this is output: ",express)
        dict_exp={}
        dict_exp["input[]"]=express
        tb,variables= Truthtable (dict_exp)
        print("tb:",tb)
        return JsonResponse({ 'results': express,
                                'table':tb,
                                'variables':variables})

Home/views.py
from django.shortcuts import render, redirect 
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages

from django.contrib.auth.decorators import login_required

# Create your views here.
from .models import *
from .forms import  CreateUserForm

# Create your views here.

def index(request):
    return render(request, 'BE_converter/Home.html')

def home1(request):
    return render(request, 'BE_converter/Home1.html')

def about(request):
    return render(request, 'BE_converter/About.html')

def help(request):
    return render(request, 'BE_converter/Help.html')



def register(request):
   if request.user.is_authenticated:
       return redirect('Home:home1-view')
   else:
	   form = CreateUserForm()
	   if request.method == 'POST':
		   form = CreateUserForm(request.POST)
		   if form.is_valid():
			   form.save()
			   user = form.cleaned_data.get('username')
			   messages.success(request, 'Account was created for ' + user)

			   return redirect('Home:login')
			

	   context = {'form':form}
	   return render(request, 'BE_converter/a.html', context)

def loginpage(request):
	if request.user.is_authenticated:
		return redirect('Home:home1-view')
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect('Home:home1-view')
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'BE_converter/login.html', context)

def logoutuser(request):
	logout(request)
	return redirect('Home:main-view')

BE_converter/templates/BE_converter/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <meta charset="utf-8">
    <title>DLD CALCULATOR</title>

    <!-- custom css & js-->
    {% block scripts %}
    {% endblock scripts %}
  </head>
  <body style="background: #d2e9f3">
    {% block content %}
    {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>

BE_converter/templates/BE_converter/logic_circuit.html
{% extends "BE_converter/base.html" %}

{% load static %}
<head> </head>
{% block scripts %}

<script type="text/javascript" src="{% static 'libraries/simcir.js'%}"></script>
    <script type="text/javascript" src="{% static 'libraries/simcir-basicset.js'%}"></script>
    <script type="text/javascript" src="{% static 'libraries/simcir-library.js'%}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'libraries/simcir.css'%}" />
	<link rel="stylesheet" type="text/css" href="{% static 'libraries/simcir-basicset.css'%}" />
	<link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.js"></script>
	<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script> 
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% endblock scripts %}

{% block content %}

<div class="title text-center py-4">  
  <div>
    <a  style=" text-decoration: none; padding-top:30px; font:10px; padding:8px; background:#0d6efd;
       border-radius:5px; color:white;" href="{% url 'Home:home1-view'%}">Home</a>
    <a  style=" text-decoration: none;padding-top:30px; font:10px; padding:8px; background:#0d6efd;
    border-radius:5px; color:white;" href="{% url 'BE_converter:expression-main-view'%}">Boolean Expression</a>
    <a  style=" text-decoration: none;padding-top:30px; font:10px; padding:8px; background:#0d6efd;
    border-radius:5px; color:white;" href="{% url 'BE_converter:circuit-main-view'%}">Logic Circuit</a>
       </div>
  <h1>Combinational circuit Converter</h1> </div>

<div class="col-auto row justify-content-center" id="show_div">  </div>
<table class="col-auto row justify-content-center" id="show_div2">  </table>
<div id="main" class="container py-4">
  <div id="mycontainer" class="p-5 mb-5 bg-light rounded-4">
      <!-- form to take logic circuit as input-->
      <div class="col-auto text-center" id="abc"> </div>
      <form id="form2" onsubmit="create(event)">
       
        <div class="row">
        <button type="submit" class="btn  btn-outline-info" id="submit">Send Data</button></div>
      </form>
      
    
      <form id="output-form">
        <div class="container">
         
          <div class="row">
           
            
                  <button type="submit" class="btn  btn-outline-danger" id="clear-workspace">Clear Workspace</button>
               
              
           
            <div class="col-lg-9 simcir_outer_div" >
              
               {% csrf_token %}
               <div class="simcir" id="mySimcir" >
                <script src="{% static 'BE_converter/logic-circuit.js' %}"></script>
              </div>
            </div>
          </div> <!--row div ends here-->

        <script type="text/javascript">
              var input = document.getElementById("fileToLoad");
              var text = document.querySelector("textarea");
              var name;
              input.onchange = function(e) {
                var reader = new FileReader();
                reader.onload = function(event) {
                  text.value = event.target.result;
                  button.disabled = false;
                }
                name = e.target.files[0].name;
                reader.readAsText(new Blob([e.target.files[0]], {
                  "type": "application/json"
                }));
              }
          </script>
        
          </div>
    <!-- div to accomodate circuit button (generated in outputCreate function in user_equation_main.js) -->
    <!-- Divs to accomodate Truthtable and Image outputs (called in
    sendData_boolean and sendData_circuit functions in user_equation_main.js ) -->
  </form>

    </div> <!--div id="mycontainer" ends here-->
</div>  <!--div id="main" ends here-->
{% endblock content %}

Home/templates/BE_converter/About.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
   <head>
      <!-- basic -->
	  <title> SIMlogical </title>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Data web</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <link rel="icon" href="{% static 'png.png' %}">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
      <style>
         .hello-msg{
           font-size: 18px;
           color: #fff;
           margin-right: 20px;
         }
       </style>
   </head>
   <!-- body -->
   <body class="main-layout">
      <!-- end loader -->
      <!-- header -->
      <header>
         <!-- header inner -->
         <div class="header">
            <div class="container">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo">
                              <img src="{% static 'png1.png' %}" width = "100" height = "70" alt="#" />
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                     <nav class="navigation navbar navbar-expand-md navbar-dark ">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarsExample04">
                           <ul class="navbar-nav mr-auto">
                              <li class="nav-item active">
                                 <a class="nav-link" href="{% url 'Home:main-view'%}">Home</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'Home:about-view'%}"> About  </a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'Home:login'%}"> Converter  </a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'Home:main-view'%}#sg">Contact</a>
                              </li>
							  <li class="nav-item">
                                 <a class="nav-link" href="{% url 'Home:help-view'%}">help</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'Home:register'%}">Signup</a>
                              </li>
                           </ul>
                        </div>
                     </nav>
                  </div>
               </div>
            </div>
         </div>
      </header>
      <!-- end header inner -->
      <!-- end header -->
      <!-- Hosting -->
      <div id="" class="hosting">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="titlepage">
                     <h2>About us</h2>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-12">
                  <div class="web_hosting">
                     <figure><img  src="{% static 'images/web.png'%}"  width = "280" height = "190"alt="#"/></figure>
                     <p>SIMlogical is a product developed by students at Fatima Jinnah Women University. 
It aims to provide a platform where circuits, Boolean Expression and Truth Table can be easily converted into each other
using a graphical user interface. Our goal is to provide a interface that is simple, friendly and convenient. We are 
passionate about the latest technologies and hope to provide you with best experience using ever-improving technologies
<br>
Happy converting!</p>

                  </div>
               </div>
            </div>
         </div>
      </div>
<footer class="footer-distributed">

			<div class="footer-left">

				<img src="{% static 'png1.png' %}" width = "180" height = "150" alt="#" />
				
				<p class="footer-company-name">SIMlogical © 2015</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>

					<p><span>Old Presidency, The Mall,</span>kachari Chowk, Rawalpindi</p>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>(051) 9292900</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:support@SIMlogical.com">support@SIMlogical.com</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-about">
					<span>About the product</span>
					We provide all conversion features in one place to fully facilitate the user.
				</p>

				<div class="footer-icons">

					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-linkedin"></i></a>
					<a href="#"><i class="fa fa-github"></i></a>

				</div>

			</div>

		</footer>
	  </html>

Home/templates/BE_converter/Home1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
   <head>
      <!-- basic -->
	  <title> SIMlogical </title>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">

      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Data web</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <link rel="icon" href="{% static 'png.png' %}">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
      <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
      <style>
         .hello-msg{
           font-size: 18px;
           color: #fff;
           margin-left:1100px;
         }
        .a{
         color: #fff;
           margin-left:20px;  
        }
       </style>
   </head>
   <!-- body -->
   <body class="main-layout">
      <!-- end loader -->
      <!-- header -->
      <header>
         <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            
            <span class="hello-msg">  Hello, {{request.user}}  </span>
            <button class="btn  btn-secondary a" ><a  href="{% url 'Home:logout' %}"> Logout </a></button>
          
          </nav>
         <!-- header inner -->
         <div class="header">
            <div class="container">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo">
                              <a href="Home.html"><img src="{% static 'png1.png' %}" width = "100" height = "70" alt="#" /></a>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                     <nav class="navigation navbar navbar-expand-md navbar-dark ">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarsExample04">
                           <ul class="navbar-nav mr-auto">
                              <li class="nav-item active">
                                 <a class="nav-link" href="{% url 'Home:main-view'%}">Home</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'Home:about-view'%}"> About  </a>
                              </li>
                              <li class="nav-item">
                                 <div class="subnav">
                                    <button class="subnavbtn"><h3>CONVERTER</h3></button>
                                    <div class="subnav-content">
                                    <a href="{% url 'BE_converter:expression-main-view'%}">Boolean Expression</a>
                                    <a href="{% url 'BE_converter:main-view'%}">Truth Table </a>
                                   <a href="{% url 'BE_converter:circuit-main-view'%}">Logic Expression</a>
                                    </div>
                                 </div>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="#sg">Contact</a>
                              </li>
							  <li class="nav-item">
                                 <a class="nav-link" href="{% url 'Home:help-view'%}">Help</a>
                              </li>
                             
                           </ul>
                        </div>
                     </nav>
                  </div>
               </div>
            </div>
         </div>
      </header>
      <!-- end header inner -->
      <!-- end header -->
      <!-- banner -->
      <section class="banner_main">
         <div class="container">
            <div class="row d_flex">
               <div class="col-md-5">
                  <div class="text-bg">
                     <h1><br>Web based design and analysis tool for digital logic circuits</h1>
                     <span>DLD made easy</span>
                     <p>SIMlogical will make conversion of truth table, circuit or algebraic expression easy.</p>
                     <a href="{% url 'BE_converter:main-view'%}">CONVERT now!</a>
                  </div>
               </div>
               <div class="col-md-7">
                  <div class="text-img">
                     <figure><img src="{% static 'last.png' %}" /></figure>
                  </div>
               </div>
            </div>
         </div>
      </section>
      <!-- end banner -->
      <!-- Hosting -->
      <div id="" class="hosting">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="titlepage">
                     <h2>How we may assist you</h2>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-12">
                  <div class="web_hosting">
                     <figure><img  src="{% static 'images/web.png'%}" width = "200" height = "170" alt="#"/></figure>
                     <p>SIMlogical is a web-based software which can be used to generate truth table or circuit using algebraic expression or vice versa.<br>
                        It will help the user to create circuits with more accuracy.</p>
                     <a href="#">Read more</a>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- end Hosting -->
      <!-- Services  -->
      <div id="service" class="Services">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="titlepage">
                     <h2>Our Services</h2>
                     <p>SIMlogical is a web-based software which can be used to generate truth table or circuit using algebraic expression or vice versa.<br>
                        It will help the user to create circuits with more accuracy.
                     </p>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                  <div class="Services-box">
                     <i><img src="{% static 'images/service1.png'%}" alt="#" /></i>
                     <h3> Boolean Expression</h3>
                     <p>A Boolean expression is a logical statement that is either TRUE or FALSE .
                        Boolean expressions can compare data of any type as long as both parts of the
                        expression have the same basic data type.</p>
                  </div>
               </div>
               <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                  <div class="Services-box">
                     <i><img src="{% static 'images/service2.png'%}" alt="#" /></i>
                     <h3>Truth Table</h3>
                     <p>A truth table is a mathematical table used in logic—specifically which sets out the
                        functional values of logical expressions. Truth tables summarize how we combine two
                        logical conditions based on AND, OR, and NOT.</p>
                  </div>
               </div>
               <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                  <div class="Services-box">
                     <i><img src="{% static 'images/service3.jpg'%}" alt="#" /></i>
                     <h3>Logic Circuit</h3>
                     <p>A logic circuit is a circuit that executes a processing or controlling function in a
                        computer. This circuit implements logical operations on information to process it. Basic
                        building block is logic gate.</p>
                  </div>
               </div>

            </div>
         </div>
      </div>
      <!-- end Servicess -->
      <!-- why -->

      <!-- contact -->
     
                  <div  id="sg" class="titlepage" style= "padding:25px;">
                     <h2>Contact us</h2>
                  </div>
               

<div class="containerr">
  <form action="/action_page.php">
    <label for="fname">First Name</label>
    <input type="text" id="fname" name="firstname" placeholder="Your name..">

    <label for="lname">Email</label>
    <input type="text" id="lname" name="lastname" placeholder="Your Email..">

    <label for="country">Country</label>
     <input type="text" id="fname" name="firstname" placeholder="Country..">

    <label for="subject">Subject</label>
    <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>

    <input type="submit" value="Submit">
  </form>
</div>

      <!-- end contact -->
      <!--  footer -->
     <footer class="footer-distributed">

			<div class="footer-left">

				<img src="{% static 'png1.png' %}" width = "180" height = "150" alt="#" />
				
				<p class="footer-company-name">SIMlogical © 2015</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>

					<p><span>Old Presidency, The Mall,</span>kachari Chowk, Rawalpindi</p>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>(051) 9292900</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:support@SIMlogical.com">support@SIMlogical.com</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-about">
					<span>About the product</span>
					We provide all conversion features in one place to fully facilitate the user.
				</p>

				<div class="footer-icons">

					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-linkedin"></i></a>
					<a href="#"><i class="fa fa-github"></i></a>

				</div>

			</div>

		</footer>
      <!-- end footer -->
      <!-- Javascript files-->
      <script src="{% static 'js/jquery.min.js"></script>
      <script src="{% static 'js/popper.min.js"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js"></script>
      <script src="{% static 'js/jquery-3.0.0.min.js"></script>
      <script src="{% static 'js/plugin.js"></script>
      <!-- sidebar -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js"></script>
      <script src="{% static 'js/custom.js"></script>
      <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
   </body>
</html>